# =============================================================================
# Stage 1: builder
# Full Node.js image with all tools needed to compile TypeScript and Vite
# =============================================================================
FROM node:22 AS builder
WORKDIR /build

# Copy workspace manifests first for layer caching
COPY package.json package-lock.json ./
COPY packages/backend/package.json packages/backend/
COPY packages/frontend/package.json packages/frontend/
COPY packages/shared/package.json packages/shared/

RUN npm ci

# Copy all source
COPY . .

# Build shared types (backend depends on this)
RUN npm run build --workspace=packages/shared

# Build backend TypeScript
RUN npm run build --workspace=packages/backend

# Build frontend (Vite)
RUN npm run build --workspace=packages/frontend

# Generate Drizzle migrations from schema
# drizzle-kit is a devDependency, available in builder; generates /build/drizzle/
RUN npx drizzle-kit generate

# =============================================================================
# Stage 2: runner
# Lean Debian slim image — NOT Alpine (Alpine musl breaks better-sqlite3 prebuilt binaries)
# =============================================================================
FROM node:22-slim AS runner
WORKDIR /app

ENV NODE_ENV=production

# Copy workspace manifests for production install
COPY package.json package-lock.json ./
COPY packages/backend/package.json packages/backend/
COPY packages/shared/package.json packages/shared/

# Install production dependencies only (no devDependencies)
RUN npm ci --omit=dev

# Copy compiled shared package
COPY --from=builder /build/packages/shared/dist ./packages/shared/dist

# Copy compiled backend output
COPY --from=builder /build/packages/backend/dist ./packages/backend/dist

# Copy compiled frontend bundle (served by Fastify via @fastify/static)
COPY --from=builder /build/packages/frontend/dist ./packages/frontend/dist

# Copy drizzle migration files (if they exist — generated by drizzle-kit)
COPY --from=builder /build/drizzle ./drizzle

# Create data directory for SQLite (will be overridden by bind mount in production)
RUN mkdir -p /app/data

EXPOSE 3000

# Health check uses the /health endpoint created in Plan 01
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD node -e "fetch('http://localhost:3000/health').then(r => r.ok ? process.exit(0) : process.exit(1)).catch(() => process.exit(1))"

CMD ["node", "packages/backend/dist/index.js"]
